name: Go Lint

on:
  workflow_call:
    inputs:
      go-version-file:
        description: 'Path to go.mod file for Go version'
        type: string
        default: 'go.mod'

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v7
        with:
          go-version-file: ${{ inputs.go-version-file }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11
